# 缓存相关常量
CACHE_TTL_DEFAULT = 3600  # 1小时
CACHE_TTL_SHORT = 300     # 5分钟
CACHE_TTL_LONG = 86400    # 24小时

# 缓存键前缀
CACHE_PREFIX_ANSWER = "answer:"
CACHE_PREFIX_IMAGE = "image:"
CACHE_PREFIX_SESSION = "session:"

# 超时设置
TIMEOUT_LLM_REQUEST = 30
TIMEOUT_VIZ_REQUEST = 15
TIMEOUT_IMAGE_GENERATION = 20

# 重试设置
MAX_RETRIES_LLM = 3
MAX_RETRIES_VIZ = 2

# 流式响应类型
STREAM_TYPE_TEXT = "text"
STREAM_TYPE_IMAGE = "image"
STREAM_TYPE_ERROR = "error"
STREAM_TYPE_DONE = "done"

# 错误代码
ERROR_CODE_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_CODE_LLM_ERROR = "LLM_ERROR"
ERROR_CODE_VIZ_ERROR = "VIZ_ERROR"
ERROR_CODE_TIMEOUT = "TIMEOUT"
ERROR_CODE_INTERNAL_ERROR = "INTERNAL_ERROR"

# 文件大小限制
MAX_IMAGE_SIZE_MB = 10
MAX_CODE_LENGTH = 10000

# 支持的图片格式
SUPPORTED_IMAGE_FORMATS = ["png", "jpg", "jpeg", "gif", "webp"] 